export const USER_SIGNUP_REQ = "USER_SIGNUP_REQ";
export const USER_SIGNUP_SUCCESS = "USER_SIGNUP_SUCCESS";
export const USER_SIGNUP_FAIL = "USER_SIGNUP_FAIL";

export const GET_ALL_USER_REQ = "GET_ALL_USER_REQ";
export const GET_ALL_USER_SUCCESS = "GET_ALL_USER_SUCCESS";
export const GET_ALL_USER_FAIL = "GET_ALL_USER_FAIL";

export const GET_ONE_USER_REQ = "GET_ONE_USER_REQ";
export const GET_ONE_USER_SUCCESS = "GET_ONE_USER_SUCCESS";
export const GET_ONE_USER_FAIL = "GET_ONE_USER_FAIL";

export const EMPLOYEE_SIGNUP_REQ = "EMPLOYEE_SIGNUP_REQ";
export const EMPLOYEE_SIGNUP_SUCCESS = "EMPLOYEE_SIGNUP_SUCCESS";
export const EMPLOYEE_SIGNUP_FAIL = "EMPLOYEE_SIGNUP_FAIL";

export const GET_ALL_EMPLOYEE_REQ = "GET_ALL_EMPLOYEE_REQ";
export const GET_ALL_EMPLOYEE_SUCCESS = "GET_ALL_EMPLOYEE_SUCCESS";
export const GET_ALL_EMPLOYEE_FAIL = "GET_ALL_EMPLOYEE_FAIL";

export const USER_LOGIN_REQ = "USER_LOGIN_REQ";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_FAIL = "USER_LOGIN_FAIL";

export const CHANGE_PASSWORD_REQ = "CHANGE_PASSWORD_REQ";
export const CHANGE_PASSWORD_SUCCESS = "CHANGE_PASSWORD_SUCCESS";
export const CHANGE_PASSWORD_FAIL = "CHANGE_PASSWORD_FAIL";

export const ADD_EMAIL_REQ = "ADD_EMAIL_REQ";
export const ADD_EMAIL_SUCCESS = "ADD_EMAIL_SUCCESS";
export const ADD_EMAIL_FAIL = "ADD_EMAIL_FAIL";

export const UPDATE_EMAIL_REQ = "UPDATE_EMAIL_REQ";
export const UPDATE_EMAIL_SUCCESS = "UPDATE_EMAIL_SUCCESS";
export const UPDATE_EMAIL_FAIL = "UPDATE_EMAIL_FAIL";

export const DELETE_EMAIL_REQ = "DELETE_EMAIL_REQ";
export const DELETE_EMAIL_SUCCESS = "DELETE_EMAIL_SUCCESS";
export const DELETE_EMAIL_FAIL = "DELETE_EMAIL_FAIL";

export const ADD_PHONE_REQ = "ADD_PHONE_REQ";
export const ADD_PHONE_SUCCESS = "ADD_PHONE_SUCCESS";
export const ADD_PHONE_FAIL = "ADD_PHONE_FAIL";

export const UPDATE_PHONE_REQ = "UPDATE_PHONE_REQ";
export const UPDATE_PHONE_SUCCESS = "UPDATE_PHONE_SUCCESS";
export const UPDATE_PHONE_FAIL = "UPDATE_PHONE_FAIL";

export const DELETE_PHONE_REQ = "DELETE_PHONE_REQ";
export const DELETE_PHONE_SUCCESS = "DELETE_PHONE_SUCCESS";
export const DELETE_PHONE_FAIL = "DELETE_PHONE_FAIL";

export const ADD_ADDRESS_REQ = "ADD_ADDRESS_REQ";
export const ADD_ADDRESS_SUCCESS = "ADD_ADDRESS_SUCCESS";
export const ADD_ADDRESS_FAIL = "ADD_ADDRESS_FAIL";

export const UPDATE_ADDRESS_REQ = "UPDATE_ADDRESS_REQ";
export const UPDATE_ADDRESS_SUCCESS = "UPDATE_ADDRESS_SUCCESS";
export const UPDATE_ADDRESS_FAIL = "UPDATE_ADDRESS_FAIL";

export const ADD_EDUCATION_REQ = "ADD_EDUCATION_REQ";
export const ADD_EDUCATION_SUCCESS = "ADD_EDUCATION_SUCCESS";
export const ADD_EDUCATION_FAIL = "ADD_EDUCATION_FAIL";

export const UPDATE_EDUCATION_REQ = "UPDATE_EDUCATION_REQ";
export const UPDATE_EDUCATION_SUCCESS = "UPDATE_EDUCATION_SUCCESS";
export const UPDATE_EDUCATION_FAIL = "UPDATE_EDUCATION_FAIL";

export const DELETE_EDUCATION_REQ = "DELETE_EDUCATION_REQ";
export const DELETE_EDUCATION_SUCCESS = "DELETE_EDUCATION_SUCCESS";
export const DELETE_EDUCATION_FAIL = "DELETE_EDUCATION_FAIL";

export const USER_LOGOUT = "USER_LOGOUT";
